#!/bin/zsh

git push heroku
heroku addons:remove mongolab:starter --confirm stark-atoll-3568
heroku addons:add mongolab:starter
heroku run rake db:seed
heroku run rake environment tire:import CLASS=Reference
heroku run rake environment tire:import CLASS=Session 
heroku run rake environment tire:import CLASS=Tag 
heroku open
